name: reuseable workflow
on:
    workflow_call:
        inputs:
            name:
                required: true
                type: string
                
jobs:
    welcome:
        runs-on: self-hosted
        steps:
        - name: welcome message
          run : echo "Hello" + ${{inputs.name}}
            